version: "3.9"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run dev
    environment:
      MONGO_URI: "mongodb://mongo:27017/whenwhere"
      PORT: 5000
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev -- --host 0.0.0.0
    environment:
      VITE_BACKEND_URL: "http://localhost:5000"
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

volumes:
  mongo-data:
  backend_node_modules:
  frontend_node_modules:
